### ISSUE TITLE
Fix code duplication because of optional clickhandler on cell

### ISSUE THREAD

**Issue by dritter** [dritter/extended-table#11]
In the code we have
```html
{#if column.clickHandler}
  <td on:click|stopPropagation={() => column.clickHandler(d)} class="{getCellClasses(columnIndex, rowIndex, column, d)}" class:hidden={column.hidden}>
    ...
    <slot ...
    ...
  </td>
{:else}
  <td>
    ....
    <slot ...
    ...
{/if}
```

So because of the clickhandler we duplicate the config for 20 slots (massive code duplication). Not sure, if there is a way to avoid this.

Unfortunately I need this click handler..

**Comment by fuzzthink** [comment]
Take a look at my edited version. You should be able to just call the handler if it exists and don't if it doesn't exists. I tested my version with both column `clickHandler` defined and `onRowClick` defined. Both are called if both are defined and `onRowClick` is still called if `clickHandler` is not defined for the col I clicked.

**Comment by dritter** [comment]
-.-'
I missed that in the first place. Thanks for the hint. I'll try your version.
